version: '3.4'

services:
  app:
    build:
      context: ./
      dockerfile: TestWebApi/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:7000
    expose:
      - "7000"
    ports:
      - "7220:22"
    restart: on-failure:5
    depends_on:
      - db
      - rabbitmq
    networks:
      main:
        aliases:
          - app

  app2:
    build:
      context: ./
      dockerfile: TestWebApi2/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:7002
    expose:
      - "7002"
    ports:
      - "7222:22"
    depends_on:
      - rabbitmq
    restart: on-failure:5
    networks:
      main:
        aliases:
          - app2

  proxy:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - "9999:80"
    depends_on:
      - app
      - app2
    networks:
      main:
        aliases:
          - proxy

  db:
    image: "microsoft/mssql-server-linux"
    environment:
        SA_PASSWORD: "QAZwsx123_longone"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      main:
        aliases:
          - db
  
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    expose:
      - "5672"
    ports:
      - "15673:15672"  # Important: In a production environment your should remove the external port
      - "5673:5672"    # Important: In a production environment your should remove the external port
    networks:
      main:
        aliases:
          - rabbitmq

networks:
  main: